---
title: 'Results'
author: Wikum Dinalankara
geometry: margin=.7cm
header-includes:
   - \usepackage{tabularx, longtable, graphicx, csquotes, hyperref, color}
output:
  html_document:
    toc: true
    number_sections: true
---
```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  dev = "png",
  fig.path = "fig/"
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.process = function(x) {
  x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
  if (file.rename(x, x2)) x2 else x
})
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

set.seed(1)

library(knitr)
library(ggplot2)
library(gridExtra)
library(grid)
library(cowplot)
library(rutils)
library(tidyr)
library(gplots)
library(ggrepel)
library(reshape2)
library(RColorBrewer)
require(switchBox)
require(Biobase)
require(limma)
require(pROC)
require(caret)
require(reshape)
require(plotROC)
library(enrichR)
library(mltools)
library(xtable)
library(boot)
library(patchwork)

```


# Breast

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=6}

l1 = load("rand_boot_breast.rda")

plots.list = utils.lapply_i(df.list, function(df, i, y){

  # ggplot(df, aes(x=auc, fill=n, group=n))+geom_density(alpha=0.4)+facet_wrap(~data+type)
  
  ggplot(df, aes(x=auc, fill=set, group=set))+geom_density(alpha=0.4)+facet_wrap(~data, ncol=1, scales="free_y")+ggtitle(y)+
    gtheme.GENERIC()+theme(strip.text.x=element_text(size=15))
  
})


```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$KTSP

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$RF

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$SVM

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$XGB

```

# Bladder

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=6}

l2 = load("rand_boot_bladder.rda")

plots.list = utils.lapply_i(df.list, function(df, i, y){

  ggplot(df, aes(x=auc, fill=set, group=set))+geom_density(alpha=0.4)+facet_wrap(~data, ncol=1, scales="free_y")+ggtitle(y)+
    gtheme.GENERIC()+theme(strip.text.x=element_text(size=15))
  
})


```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$KTSP

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$RF

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$SVM

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$XGB

```


# Prostate

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=6}

l3 = load("rand_boot_prostate.rda")

plots.list = utils.lapply_i(df.list, function(df, i, y){

  ggplot(df, aes(x=auc, fill=set, group=set))+geom_density(alpha=0.4)+facet_wrap(~data, ncol=1, scales="free_y")+ggtitle(y)+
    gtheme.GENERIC()+theme(strip.text.x=element_text(size=15))
  
})


```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$KTSP

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$RF

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$SVM

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}

plots.list$XGB

```


